export default [
  {
    name: "Rap God",
    created_at: new Date("2021-01-01"),
    cover_img: "rap.jpg",
    songs: [
      "gOMhN-hfMtY",
      "eJO5HU_7_1w",
      "S9bCLPwzSC0",
      "lexLAjh8fPA",
      "2a8PgqWrc_4",
      "6ONRf7h3Mdk",
      "dJ7bquKFC4E",
    ],
  },
  {
    name: "Rock N Roll",
    created_at: new Date("2021-01-03"),
    cover_img: "rock.jpg",
    songs: [
      "o1tj2zJ2Wvg",
      "Rbm6GXllBiw",
      "ulvmdYMyT80",
      "1w7OgIMMRc4",
      "zP2Kw3xvgYU",
      "ErvgV4P6Fzc",
    ],
  },
  {
    name: "Mix It",
    created_at: new Date("2021-02-02"),
    cover_img: "mix.jpg",
    songs: [
      "6ONRf7h3Mdk",
      "87gWaABqGYs",
      "dAlRXC19hmE",
      "ErvgV4P6Fzc",
      "9dcVOmEQzKA",
    ],
  },
  {
    name: "Pop",
    created_at: new Date("2021-06-01"),
    cover_img: "pop.jpg",
    songs: [
      "87gWaABqGYs",
      "K0ibBPhiaG0",
      "JGwWNGJdvx8",
      "c4BLVznuWnU",
      "FOjdXSrtUxA",
      "UAWcs5H-qgQ",
    ],
  },
  {
    name: "Road Trip",
    created_at: new Date("2021-03-03"),
    cover_img: "road_trip.jpg",
    songs: [
      "Shape of You",
      "Rbm6GXllBiw",
      "ngzC_8zqInk",
      "o1tj2zJ2Wvg",
      "UAWcs5H-qgQ",
      "eJO5HU_7_1w",
    ],
  },
];
